In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.ndim)
newarr = arr.reshape(4, 3)
print(newarr.ndim)
print(newarr)

1
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
#Reshape From 1-D to 3-D
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
#We can not pass -1 to more than one dimension
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
#Convert the array into a 1D array
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
